"""
Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 
terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
"""

def eu002(lim = 4 * 1000 * 1000):

    
    a, b = 1, 2
    sum = 2
    
    while b < lim:
        a, b = b, a + b       # <-- tuple assignment to avoid tmp var
        if not b % 2: sum += b
    
    return sum
    
def eu002_alt(lim):
    """Alternative solution using generator"""
    
    a, b = 1, 2
    
    while a < lim:
        if not a % 2: yield a
        a, b = b, a + b       # <-- tuple assignment to avoid tmp var
        